<?php

use CustomPost\Fields\Field;
use CustomPost\Fields\Subtype;
use Realworks\Common\PrimaryKeySelector;
use Realworks\Wonen\Selectors\CitySelector;
use Realworks\Wonen\Selectors\AddressSelector;

return array(
	Field::int('id')->select(new PrimaryKeySelector)->primary()->unique(),
	Field::string('user'),
	Field::string('NVMVestigingNR')->select('./NVMVestigingNR'),
	Field::string('objectCompany')->select('./ObjectCompany'),
	Field::string('objectAfdeling')->select('./ObjectAfdeling'),
	Field::int('objectTiaraID')->select('./ObjectTiaraID'),
	Field::int('objectSystemID')->select('./ObjectSystemID'),
	Field::string('objectCode')->select('./ObjectCode'),
	Field::string('adres')->select(new AddressSelector),
	Field::string('plaats')->select(new CitySelector)->formatter('Realworks\Common\Formatters\CityFormatter')->hasVirtualDependency(true),
	Subtype::make('adresNederlands', './ObjectDetails/Adres/Nederlands', array(
		Field::string('straatnaam')->select('./Straatnaam'),
		Field::int('huisnummer')->select('./Huisnummer'),
		Field::string('huisnummerToevoeging')->select('./HuisnummerToevoeging'),
		Field::string('postcode')->select('./Postcode'),
		Field::string('plaats')->select('./Woonplaats'),
		Field::string('gemeente')->select('./Gemeente'),
		Field::string('land')->select('./Land'),
	)),
	Subtype::make('adresInternationaal', './ObjectDetails/Adres/Internationaal', array(
		Field::string('adresregel1')->select('./Adresregel1'),
		Field::string('adresregel2')->select('./Adresregel2'),
		Field::string('plaats')->select('./Woonplaats'),
		Field::string('land')->select('./Land'),
	)),
	Field::string('koopprijsVoorvoegsel')->select('./ObjectDetails/Koop/Prijsvoorvoegsel'),
	Field::int('koopprijs')->select('./ObjectDetails/Koop/Koopprijs')->formatter('money'),
	Field::string('koopconditie')->select('./ObjectDetails/Koop/KoopConditie'),
	Field::string('koopspecificatie')->select('./ObjectDetails/Koop/KoopSpecificatie'),
	Field::int('WOZWaarde')->select('./ObjectDetails/Koop/WOZ/WOZWaarde')->formatter('money'),
	Field::date('WOZWaardePeildatum')->select('./ObjectDetails/Koop/WOZ/WOZWaardePeildatum')->parseFormat('Y-m-d'),
	Field::int('huurprijs')->select('./ObjectDetails/Huur/Huurprijs')->formatter('money'),
	Field::string('huurconditie')->select('./ObjectDetails/Huur/HuurConditie'),
	Field::string('huurspecificatie')->select('./ObjectDetails/Huur/HuurSpecificatie'),
	Field::int('servicekostenPerMaand')->select('./ObjectDetails/ServicekostenPerMaand')->formatter('money'),
	Field::string('aanvaarding')->select('./ObjectDetails/Aanvaarding'),
	Field::date('datumAanvaarding')->select('./ObjectDetails/DatumAanvaarding')->parseFormat('Y-m-d'),
	Field::string('toelichtingAanvaarding')->select('./ObjectDetails/ToelichtingAanvaarding'),
	Field::string('objectAanmelding')->select('./ObjectDetails/ObjectAanmelding'),
	Field::string('koopmengvorm')->select('./ObjectDetails/Koopmengvorm/Mengvorm'),
	Field::int('koopmengvormAfwijkingVanKoopprijs')->select('./ObjectDetails/Koopmengvorm/AfwijkingVanKoopprijs'),
	Field::text('koopmengvormToelichting')->select('./ObjectDetails/Koopmengvorm/Toelichting'),
	Field::date('datumInvoer')->select('./ObjectDetails/DatumInvoer')->parseFormat('Y-m-d'),
	Field::date('datumWijziging')->select('./ObjectDetails/DatumWijziging')->parseFormat('Y-m-d'),
	Field::date('datumVeiling')->select('./ObjectDetails/DatumVeiling')->parseFormat('Y-m-d'),
	Field::string('status')->select('./ObjectDetails/StatusBeschikbaarheid/Status')->values(array(
		'Beschikbaar' => 'Beschikbaar',
		'Onder bod' => 'Onder bod',
		'Onder optie' => 'Onder optie',
		'Verkocht onder voorbehoud' => 'Verkocht onder voorbehoud',
		'Verhuurd onder voorbehoud' => 'Verhuurd onder voorbehoud',
		'Verkocht' => 'Verkocht',
		'Verhuurd' => 'Verhuurd',
		'Ingetrokken' => 'Ingetrokken',
		'Geveild' => 'Geveild',
	)),
	Field::date('verkochtOnderVoorbehoudDatum')->select('./ObjectDetails/StatusBeschikbaarheid/VerkochtOnderVoorbehoud/Datum')->parseFormat('Y-m-d'),
	Field::date('verkochtOnderVoorbehoudDatumTot')->select('./ObjectDetails/StatusBeschikbaarheid/VerkochtOnderVoorbehoud/DatumVoorbehoudTot')->parseFormat('Y-m-d'),
	Field::date('transactieDatum')->select('./ObjectDetails/StatusBeschikbaarheid/TransactieDatum')->parseFormat('Y-m-d'),
	Field::string('bouwvorm')->select('./ObjectDetails/Bouwvorm'),
	Field::string('internetplaatsingen')->select('./ObjectDetails/Internetplaatsingen/Internetplaatsing/Plaatsing'),
	Field::text('aanbiedingstekst')->select('./ObjectDetails/Aanbiedingstekst'),
	Subtype::make('BOGObject', './ObjectDetails/CombinatieObject/BOGObject', array(
		Field::string('type')->select('./Type'),
		Field::string('situatie')->select('./Situatie'),
		Field::int('objectID')->select('./ObjectID'),
		Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
		Field::string('status')->select('./Status'),
	)),
	Subtype::make('agrarischBedrijf', './ObjectDetails/CombinatieObject/AgrarischBedrijf', array(
		Field::int('objectID')->select('./ObjectID'),
	)),
	Subtype::make('woning', './Wonen', array(
		Field::string('huidigGebruik')->select('./WonenDetails/Bestemming/HuidigGebruik'),
		Field::string('huidigeBestemming')->select('./WonenDetails/Bestemming/HuidigeBestemming'),
		Field::boolean('permanenteBewoning')->select('./WonenDetails/Bestemming/PermanenteBewoning')->trueValue('ja'),
		Field::boolean('recreatiewoning')->select('./WonenDetails/Bestemming/Recreatiewoning')->trueValue('ja'),
		Field::listing('liggingen')->select('./WonenDetails/MatenEnLigging/Liggingen/Ligging'),
		Field::int('inhoud')->select('./WonenDetails/MatenEnLigging/Inhoud')->formatter('volume'),
		Field::int('gebruiksoppervlakteWoonfunctie')->select('./WonenDetails/MatenEnLigging/GebruiksoppervlakteWoonfunctie')->formatter('area'),
		Field::int('gebruiksoppervlakteOverigeFuncties')->select('./WonenDetails/MatenEnLigging/GebruiksoppervlakteOverigeFuncties')->formatter('area'),
		Field::int('buitenruimtesGebouwgebondenOfVrijstaand')->select('./WonenDetails/MatenEnLigging/BuitenruimtesGebouwgebondenOfVrijstaand')->formatter('area'),
		Field::int('perceelOppervlakte')->select('./WonenDetails/MatenEnLigging/PerceelOppervlakte')->formatter('area'),
		Field::string('bouwjaar')->select('./WonenDetails/Bouwjaar/JaarOmschrijving/Jaar'),
		Field::string('bouwjaarOmschrijving')->select('./WonenDetails/Bouwjaar/JaarOmschrijving/Omschrijving'),
		Field::string('bouwjaarPeriode')->select('./WonenDetails/Bouwjaar/Periode'),
		Field::boolean('inAanbouw')->select('./WonenDetails/Bouwjaar/InAanbouw')->trueValue('ja'),
		Subtype::make('onderhoudBinnen', './WonenDetails/Onderhoud/Binnen', array(
			Field::string('waardering')->select('./Waardering'),
			Field::text('memo')->select('./Memo'),
		)),
		Subtype::make('onderhoudBuiten', './WonenDetails/Onderhoud/Buiten', array(
			Field::string('waardering')->select('./Waardering'),
			Field::text('memo')->select('./Memo'),
		)),
		Subtype::make('schuurBerging', './WonenDetails/SchuurBerging', array(
			Field::string('soort')->select('./Soort'),
			Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
			Field::listing('isolatievormen')->select('./Isolatievormen/Isolatie'),
			Field::int('totaalAantal')->select('./TotaalAantal'),
		)),
		Field::listing('bijzonderheden')->select('./WonenDetails/Diversen/Bijzonderheden/Bijzonderheid'),
		Field::listing('isolatievormen')->select('./WonenDetails/Diversen/Isolatievormen/Isolatie'),
		Field::string('dakType')->select('./WonenDetails/Diversen/Dak/Type'),
		Field::listing('dakMaterialen')->select('./WonenDetails/Diversen/Dak/Materialen/Materiaal'),
		Field::text('dakToelichting')->select('./WonenDetails/Diversen/Dak/Toelichting'),
		Field::listing('keurmerken')->select('./WonenDetails/Keurmerken/Keurmerk'),
		Field::string('energieklasse')->select('./WonenDetails/Energielabel/Energieklasse'),
		Field::string('energieIndex')->select('./WonenDetails/Energielabel/EnergieIndex'),
		Field::date('energielabelEinddatum')->select('./WonenDetails/Energielabel/Einddatum')->parseFormat('Y-m-d'),
		Field::string('EPC')->select('./WonenDetails/EPC'),
		Subtype::make('installatie', './WonenDetails/Installatie', array(
			Field::listing('soortenVerwarming')->select('./SoortenVerwarming/Verwarming'),
			Field::string('CVKetelType')->select('./CVKetel/CVKetelType'),
			Field::string('CVKetelBouwjaar')->select('./CVKetel/Bouwjaar'),
			Field::string('CVKetelBrandstof')->select('./CVKetel/Brandstof'),
			Field::string('CVKetelEigendom')->select('./CVKetel/Eigendom'),
			Field::boolean('CVKetelCombiketel')->select('./CVKetel/Combiketel')->trueValue('ja'),
			Field::listing('soortenWarmWater')->select('./SoortenWarmWater/WarmWater'),
		)),
		Field::listing('voorzieningen')->select('./WonenDetails/VoorzieningenWonen/Voorziening'),
		Field::text('toelichting')->select('./WonenDetails/Toelichting'),
		Subtype::make('tuin', './WonenDetails/Tuin', array(
			Field::listing('tuintypen')->select('./Tuintypen/Tuintype'),
			Field::string('kwaliteit')->select('./Kwaliteit'),
			Field::int('totaleOppervlakte')->select('./TotaleOppervlakte')->formatter('area'),
		)),
		Subtype::make('hoofdtuin', './WonenDetails/Hoofdtuin', array(
			Field::string('type')->select('./Type'),
			Field::string('positie')->select('./Positie'),
			Field::boolean('achterom')->select('./Achterom')->trueValue('ja'),
			Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
			Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
			Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
		)),
		Subtype::make('garage', './WonenDetails/Garage', array(
			Field::listing('soorten')->select('./Soorten/Soort'),
			Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
			Field::int('capaciteit')->select('./Capaciteit'),
			Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
			Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
			Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			Field::listing('isolatievormen')->select('./Isolatievormen/Isolatie'),
			Field::int('totaalAantalGarages')->select('./TotaalAantalGarages'),
		)),
		Field::listing('parkeerFaciliteiten')->select('./WonenDetails/Parkeren/Faciliteiten/Faciliteit'),
		Field::text('parkerenToelichting')->select('./WonenDetails/Parkeren/Toelichting'),
		Subtype::make('woonhuis', './Woonhuis', array(
			Field::string('soort')->select('./SoortWoning'),
			Field::string('type')->select('./TypeWoning'),
			Field::string('kenmerk')->select('./KenmerkWoning'),
			Field::string('kwaliteit')->select('./KwaliteitWoning'),
		)),
		Subtype::make('appartement', './Appartement', array(
			Field::string('soort')->select('./SoortAppartement'),
			Field::string('kenmerk')->select('./KenmerkAppartement'),
			Field::string('kwaliteit')->select('./Kwaliteit'),
			Field::boolean('openPortiek')->select('./OpenPortiek')->trueValue('ja'),
			Field::int('woonlaag')->select('./Woonlaag'),
			Field::int('aantalWoonlagen')->select('./AantalWoonlagen'),
			Field::boolean('VVEChecklistAanwezig')->select('./VVEChecklistAanwezig')->trueValue('ja'),
		)),
		Field::int('aantalVerdiepingen')->select('./Verdiepingen/Aantal'),
		Field::int('aantalKamers')->select('./Verdiepingen/AantalKamers'),
		Field::int('aantalSlaapkamers')->select('./Verdiepingen/AantalSlaapKamers'),
		Subtype::make('kelder', './Woonlagen/Kelder', array(
			Field::int('verdiepingNr')->select('./VerdiepingNr'),
			Field::string('naam')->select('./Naam'),
			Field::int('aantalKamers')->select('./AantalKamers'),
			Field::int('aantalSlaapkamers')->select('./AantalSlaapkamers'),
			Subtype::make('woonkamer', './Woonkamer', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::boolean('trap')->select('./Trap')->trueValue('ja'),
			)),
			Subtype::make('keuken', './Keuken', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::int('vernieuwd')->select('./Vernieuwd'),
			)),
			Subtype::make('badkamer', './Badkamer[0]', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Subtype::collection('badkamers', './Badkamer', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Field::listing('overigeRuimten')->select('./OverigeRuimten/OverigeRuimte'),
		)),
		Subtype::make('beganeGrondOfFlat', './Woonlagen/BeganeGrondOfFlat', array(
			Field::int('verdiepingNr')->select('./VerdiepingNr'),
			Field::string('naam')->select('./Naam'),
			Field::int('aantalKamers')->select('./AantalKamers'),
			Field::int('aantalSlaapkamers')->select('./AantalSlaapkamers'),
			Subtype::make('woonkamer', './Woonkamer', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::string('trap')->select('./Trap'),
			)),
			Subtype::make('keuken', './Keuken', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::int('vernieuwd')->select('./Vernieuwd'),
			)),
			Subtype::make('badkamer', './Badkamer[0]', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Subtype::collection('badkamers', './Badkamer', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Field::listing('overigeRuimten')->select('./OverigeRuimten/OverigeRuimte'),
		)),
		Subtype::make('verdieping', './Woonlagen/Verdieping[0]', array(
			Field::int('verdiepingNr')->select('./VerdiepingNr'),
			Field::string('naam')->select('./Naam'),
			Field::int('aantalKamers')->select('./AantalKamers'),
			Field::int('aantalSlaapkamers')->select('./AantalSlaapkamers'),
			Subtype::make('woonkamer', './Woonkamer', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::string('trap')->select('./Trap'),
			)),
			Subtype::make('keuken', './Keuken', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::int('vernieuwd')->select('./Vernieuwd'),
			)),
			Subtype::make('badkamer', './Badkamer[0]', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Subtype::collection('badkamers', './Badkamer', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Field::listing('overigeRuimten')->select('./OverigeRuimten/OverigeRuimte'),
		)),
		Subtype::collection('verdiepingen', './Woonlagen/Verdieping', array(
			Field::int('verdiepingNr')->select('./VerdiepingNr'),
			Field::string('naam')->select('./Naam'),
			Field::int('aantalKamers')->select('./AantalKamers'),
			Field::int('aantalSlaapkamers')->select('./AantalSlaapkamers'),
			Subtype::make('woonkamer', './Woonkamer', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::string('trap')->select('./Trap'),
			)),
			Subtype::make('keuken', './Keuken', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::int('vernieuwd')->select('./Vernieuwd'),
			)),
			Subtype::make('badkamer', './Badkamer[0]', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Subtype::collection('badkamers', './Badkamer', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Field::listing('overigeRuimten')->select('./OverigeRuimten/OverigeRuimte'),
		)),
		Subtype::make('zolder', './Woonlagen/Zolder', array(
			Field::int('verdiepingNr')->select('./VerdiepingNr'),
			Field::string('naam')->select('./Naam'),
			Field::int('aantalKamers')->select('./AantalKamers'),
			Field::int('aantalSlaapkamers')->select('./AantalSlaapkamers'),
			Subtype::make('woonkamer', './Woonkamer', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::string('trap')->select('./Trap'),
			)),
			Subtype::make('keuken', './Keuken', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::int('vernieuwd')->select('./Vernieuwd'),
			)),
			Subtype::make('badkamer', './Badkamer[0]', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Subtype::collection('badkamers', './Badkamer', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Field::listing('overigeRuimten')->select('./OverigeRuimten/OverigeRuimte'),
			Field::listing('zolderVlieringOpties')->select('./ZolderVlieringOpties/ZolderVlieringOptie'),
		)),
		Subtype::make('vliering', './Woonlagen/Vliering', array(
			Field::int('verdiepingNr')->select('./VerdiepingNr'),
			Field::string('naam')->select('./Naam'),
			Field::int('aantalKamers')->select('./AantalKamers'),
			Field::int('aantalSlaapkamers')->select('./AantalSlaapkamers'),
			Subtype::make('woonkamer', './Woonkamer', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::string('trap')->select('./Trap'),
			)),
			Subtype::make('keuken', './Keuken', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::int('vernieuwd')->select('./Vernieuwd'),
			)),
			Subtype::make('badkamer', './Badkamer[0]', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Subtype::collection('badkamers', './Badkamer', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Field::listing('overigeRuimten')->select('./OverigeRuimten/OverigeRuimte'),
			Field::listing('zolderVlieringOpties')->select('./ZolderVlieringOpties/ZolderVlieringOptie'),
		)),
	)),
	Subtype::make('bouwgrond', './Bouwgrond', array(
		Field::string('huidigeBestemming')->select('./HuidigeBestemming'),
		Field::string('huidigGebruik')->select('./HuidigGebruik'),
		Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
		Field::string('bouwrijp')->select('./Bouwrijp'),
		Field::listing('liggingen')->select('./Liggingen/Ligging'),
		Field::text('toelichting')->select('./Toelichting'),
	)),
	Subtype::make('inpandigeGarage', './OverigOG/InpandigeGarage', array(
		Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
		Field::int('capaciteit')->select('./Capaciteit'),
		Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
		Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
		Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
		Field::listing('isolatievormen')->select('./Isolatievormen/Isolatie'),
		Field::text('toelichting')->select('./Toelichting'),
	)),
	Subtype::make('garagebox', './OverigOG/Garagebox', array(
		Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
		Field::int('capaciteit')->select('./Capaciteit'),
		Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
		Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
		Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
		Field::listing('isolatievormen')->select('./Isolatievormen/Isolatie'),
		Field::text('toelichting')->select('./Toelichting'),
	)),
	Subtype::make('parkeerkelder', './OverigOG/Parkeerkelder', array(
		Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
		Field::int('capaciteit')->select('./Capaciteit'),
		Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
		Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
		Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
		Field::text('toelichting')->select('./Toelichting'),
	)),
	Subtype::make('parkeerplaats', './OverigOG/Parkeerplaats', array(
		Field::int('capaciteit')->select('./Capaciteit'),
		Field::text('toelichting')->select('./Toelichting'),
	)),
	Subtype::make('berging', './OverigOG/Berging', array(
		Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
		Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
		Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
		Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
		Field::listing('isolatievormen')->select('./Isolatievormen/Isolatie'),
		Field::text('toelichting')->select('./Toelichting'),
	)),
	Subtype::make('woonwagenStandplaats', './OverigOG/Woonwagenstandplaats', array(
		Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
		Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
		Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
		Field::text('toelichting')->select('./Toelichting'),
	)),
	Subtype::make('stacaravanStandplaats', './OverigOG/Stacaravanstandplaats', array(
		Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
		Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
		Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
		Field::text('toelichting')->select('./Toelichting'),
	)),
	Subtype::make('ligplaats', './OverigOG/Ligplaats', array(
		Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
		Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
		Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
		Field::text('toelichting')->select('./Toelichting'),
	)),
	Subtype::collection('medialijst', './MediaLijst/Media', array(
		Field::string('groep')->select('./Groep'),
		Field::string('url')->select('./URL')->length(1000),
		Field::string('omschrijving')->select('./MediaOmschrijving')->length(1000),
		Field::date('gewijzigd')->select('./LaatsteWijziging')->parseFormat('Y-m-d\TH:i:s'),
	)),
	Field::boolean('prijsTonen')->select('./Web/PrijsTonen')->trueValue('ja'),
	Field::datetime('openHuisVanaf')->select('./Web/OpenHuis/Vanaf')->parseFormat('Y-m-d\TH:i:s'),
	Field::datetime('openHuisTot')->select('./Web/OpenHuis/Tot')->parseFormat('Y-m-d\TH:i:s'),
	Field::int('prioriteit')->select('./Web/Prioriteit'),
	Field::text('magazine')->select('./Web/Magazine'),
	Field::text('korteOmschrijving')->select('./Web/KorteOmschrijving'),
);
