<?php

use CustomPost\Fields\Field;
use CustomPost\Fields\Subtype;
use Realworks\Common\PrimaryKeySelector;
use Realworks\Bog\Selectors\AddressSelector;

return array(
	Field::int('id')->select(new PrimaryKeySelector)->primary()->unique(),
	Field::string('user'),
	Field::string('NVMVestigingNR')->select('./NVMVestigingNR'),
	Field::string('objectCompany')->select('./ObjectCompany'),
	Field::string('objectAfdeling')->select('./ObjectAfdeling'),
	Field::int('objectTiaraID')->select('./ObjectTiaraID'),
	Field::int('objectSystemID')->select('./ObjectSystemID'),
	Field::string('objectCode')->select('./ObjectCode'),
	Field::string('adres')->select(new AddressSelector),
	Field::string('plaats')->select('./ObjectDetails/Adres/Nederlands/Woonplaats')->hasVirtualDependency(true),
	Subtype::make('adresNederlands', './ObjectDetails/Adres/Nederlands', array(
		Field::string('straatnaam')->select('./Straatnaam'),
		Field::string('hoofdnummer')->select('./Huisnummer/Hoofdnummer'),
		Field::int('reeksBegin')->select('./Huisnummer/Reeks/Begin'),
		Field::int('reeksEind')->select('./Huisnummer/Reeks/Eind'),
		Field::string('huisnummerToevoeging')->select('./HuisnummerToevoeging'),
		Field::string('postcode')->select('./Postcode'),
		Field::string('woonplaats')->select('./Woonplaats'),
	)),
	Subtype::make('huur', './ObjectDetails/Huur', array(
		Field::int('prijs')->select('./PrijsSpecificatie/Prijs')->formatter('money'),
		Field::string('prijsvoorvoegsel')->select('./PrijsSpecificatie/Prijsvoorvoegsel'),
		Field::int('prijsVan')->select('./PrijsSpecificatie/PrijsVan')->formatter('money'),
		Field::int('prijsTot')->select('./PrijsSpecificatie/PrijsTot')->formatter('money'),
		Field::string('BTWTarief'),
		Field::boolean('BTWBelast')->select('./PrijsSpecificatie/BTWBelast'),
		Subtype::make('servicekosten', './PrijsSpecificatie/Servicekosten', array(
			Field::int('prijs')->select('./PrijsSpecificatie/Prijs')->formatter('money'),
			Field::string('BTWTarief'),
			Field::boolean('BTWBelast')->select('./PrijsSpecificatie/BTWBelast'),
			Field::boolean('bouwrente'),
			Field::string('conditie')->select('./ServicekostenConditie'),
		)),
		Field::boolean('bouwrente'),
		Field::string('huurConditie')->select('./HuurConditie'),
	)),
	Subtype::make('koop', './ObjectDetails/Koop', array(
		Field::int('prijs')->select('./PrijsSpecificatie/Prijs')->formatter('money'),
		Field::string('prijsvoorvoegsel')->select('./PrijsSpecificatie/Prijsvoorvoegsel'),
		Field::string('BTWTarief'),
		Field::boolean('BTWBelast')->select('./PrijsSpecificatie/BTWBelast'),
		Subtype::make('servicekosten', '.', array(
			Field::int('prijs')->formatter('money'),
			Field::string('BTWTarief'),
			Field::boolean('BTWBelast'),
			Field::string('bouwrente'),
			Field::string('conditie'),
		)),
		Field::boolean('bouwrente'),
		Field::string('koopConditie')->select('./KoopConditie'),
		Subtype::make('belegging', '../../Functies/Belegging', array(
			Field::string('aantalHuurders')->select('./AantalHuurders'),
			Field::int('brutoHuuropbrengstPrijs')->select('./BrutoHuuropbrengstKaleHuur')->formatter('money'),
			Field::string('brutoHuuropbrengstBTWTarief'),
			Field::boolean('brutoHuuropbrengstBTWBelast')->select('./BTWBelast'),
			Field::date('expiratiedatum')->parseFormat('Y-m-d'),
		)),
	)),
	Field::string('typeAanvaarding')->select('./ObjectDetails/Aanvaarding'),
	Field::date('datumAanvaarding')->select('./ObjectDetails/DatumAanvaarding')->parseFormat('Y-m-d'),
	Field::string('toelichtingAanvaarding'),
	Field::string('objectAanmelding')->select('./ObjectDetails/ObjectAanmelding'),
	Field::date('datumInvoer')->select('./ObjectDetails/DatumInvoer')->parseFormat('Y-m-d'),
	Field::date('datumWijziging')->select('./ObjectDetails/DatumWijziging')->parseFormat('Y-m-d\TH:i:s'),
	Field::string('status')->select('./ObjectDetails/StatusBeschikbaarheid/Status')->values(array(
		'beschikbaar' => 'Beschikbaar',
		'onder bod' => 'Onder bod',
		'onder optie' => 'Onder optie',
		'verkocht onder voorbehoud' => 'Verkocht onder voorbehoud',
		'verhuurd onder voorbehoud' => 'Verhuurd onder voorbehoud',
		'verhuurd' => 'Verhuurd',
		'verkocht' => 'Verkocht',
		'geveild' => 'Geveild',
		'verkochtbijinschrijving' => 'Verkocht bij inschrijving',
		'ingetrokken' => 'Ingetrokken',
	)),
	Field::date('datumVoorbehoudTot')->select('./ObjectDetails/Status/DatumVoorbehoudTot')->parseFormat('Y-m-d'),
	Field::date('transactieDatum')->select('./ObjectDetails/Status/TransactieDatum')->parseFormat('Y-m-d'),
	Field::string('bouwvorm')->select('./ObjectDetails/Bouwvorm'),
	Field::text('aanbiedingstekst')->select('./ObjectDetails/Aanbiedingstekst'),
	Field::int('oppervlaktePerceel')->select('./ObjectDetails/OppervlaktePerceel')->formatter('area'),
	Field::string('hoofdbestemming')->select('./ObjectDetails/Hoofdfunctie'),
	Field::listing('nevenbestemmingen'),
	Subtype::make('woonobject', './ObjectDetails/Woonobject', array(
		Field::string('situatie')->select('./Situatie'),
		Field::int('objectID')->select('./ObjectID'),
		Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
		Field::string('status')->select('./Status'),
	)),
	Subtype::make('gebouw', '.', array(
		Subtype::make('gebouwDetails', './GebouwDetails', array(
			Subtype::collection('bouwjaren', './Bouwjaar/JaarOmschrijving', array(
				Field::int('jaar')->select('./Jaar'),
				Field::string('omschrijving')->select('./Omschrijving'),
			)),
			Field::string('bouwjaarPeriode')->select('./Bouwjaar/Periode'),
			Field::boolean('inAanbouw')->select('./Bouwjaar/InAanbouw'),
			Subtype::make('onderhoudBinnen', './Onderhoud/Binnen', array(
				Field::listing('waarderingen')->select('./Waardering'),
				Field::text('memo')->select('./Memo'),
			)),
			Subtype::make('onderhoudBuiten', './Onderhoud/Buiten', array(
				Field::listing('waarderingen')->select('./Waardering'),
				Field::text('memo')->select('./Memo'),
			)),
			Field::listing('liggingen')->select('./Lokatie/Liggingen/Ligging'),
            Subtype::make('bereikbaarheid', './Lokatie/Bereikbaarheid', array(
                Field::string('snelwegAfrit')->select('./SnelwegAfrit'),
                Field::string('station')->select('./NS-station'),
                Field::string('bushalte')->select('./Bushalte'),
            )),
			Subtype::make('parkeren', './Lokatie/Parkeren', array(
				Field::text('parkeerfaciliteiten')->select('./Parkeerfaciliteiten'),
				Field::int('prijs')->select('./NietOverdekteParkeerplaatsen/PrijsSpecificatie/Prijs')->formatter('money'),
				Field::string('BTWTarief'),
				Field::boolean('BTWBelast')->select('./NietOverdekteParkeerplaatsen/PrijsSpecificatie/BTWBelast'),
				Field::boolean('bouwrente'),
				Field::int('aantal')->select('./NietOverdekteParkeerplaatsen/Aantal'),
			)),
            Subtype::make('energielabel', './Energielabel', array(
                Field::string('klasse')->select('./Energieklasse'),
                Field::string('index')->select('./EnergieIndex'),
                Field::date('einddatum')->select('./Einddatum')->parseFormat('Y-m-d'),
            )),
			Field::text('lokatieToelichting')->select('./Lokatie/Toelichting'),
		)),
		Subtype::make('bedrijfsruimte', './Functies/Bedrijfsruimte', array(
			Subtype::make('bedrijfshal', './Bedrijfshal', array(
				Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
				Field::int('inUnitsVanaf')->select('./InUnitsVanaf'),
				Field::int('vrijeHoogte')->select('./VrijeHoogte'),
				Field::int('vrijeOverspanning')->select('./VrijeOverspanning'),
				Field::int('vloerbelasting')->select('./Vloerbelasting'),
				Field::listing('luchtbehandelingen')->select('./Luchtbehandelingen/Luchtbehandeling'),
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('prijs')->select('./PrijsSpecificatie/Prijs')->formatter('money'),
				Field::string('BTWTarief'),
				Field::boolean('BTWBelast')->select('./PrijsSpecificatie/BTWBelast'),
				Field::boolean('bouwrente'),
			)),
			Subtype::make('kantoorruimte', './Kantoorruimte', array(
				Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
				Field::int('verdiepingen')->select('./Verdiepingen'),
				Field::listing('luchtbehandelingen')->select('./Luchtbehandelingen/Luchtbehandeling'),
				Field::listing('opleveringsniveau')->select('./Opleveringsniveau/Voorziening'),
				Field::int('prijs')->select('./PrijsSpecificatie/Prijs')->formatter('money'),
				Field::string('BTWTarief'),
				Field::boolean('BTWBelast')->select('./PrijsSpecificatie/BTWBelast'),
				Field::boolean('bouwrente'),
			)),
			Subtype::make('terrein', './Terrein', array(
				Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
				Subtype::make('uitbreidingsmogelijkheden', './Uitbreidingsmogelijkheden', array(
					Field::int('procentueel')->select('./Procentueel'),
					Field::int('inVierkanteMeters')->select('./InVierkanteMeters'),
					Field::int('bouwhoogte')->select('./Bouwhoogte'),
				)),
				Field::int('prijs')->select('./PrijsSpecificatie/Prijs')->formatter('money'),
				Field::string('BTWTarief'),
				Field::boolean('BTWBelast')->select('./PrijsSpecificatie/BTWBelast'),
				Field::boolean('bouwrente'),
			)),
		)),
		Subtype::make('horeca', './Functies/Horeca', array(
			Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
			Field::int('verkoopVloeroppervlakte')->select('./VerkoopVloeroppervlakte')->formatter('area'),
			Field::listing('gelegenOpVerdieping')->select('./GelegenOpVerdieping/Verdieping'),
			Field::listing('regios')->select('./Regios/Regio'),
			Field::listing('soortHoreca')->select('./Drankensector/HorecaTypen/HorecaType|./Fastfoodsector/HorecaTypen/HorecaType|./Restaurantsector/HorecaTypen/HorecaType|./Hotelsector/HorecaTypen/HorecaType'),
			Field::int('goodwillPrijs')->select('./TerOvername/PrijsInventarisGoodwill/Prijs')->formatter('money'),
			Field::string('goodwillBTWTarief'),
			Field::boolean('goodwillBTWBelast')->select('./TerOvername/PrijsGoodwill/BTWBelast'),
			Field::boolean('terOvernamePersoneel')->select('./TerOvername/Personeel'),
			Field::string('welstandsklasse')->select('./Welstandsklasse'),
		)),
		Subtype::make('kantoorruimte', './Functies/Kantoorruimte', array(
			Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
			Field::int('inUnitsVanaf')->select('./InUnitsVanaf'),
			Field::listing('luchtbehandelingen')->select('./Luchtbehandelingen/Luchtbehandeling'),
			Field::int('verdiepingen')->select('./Verdiepingen'),
			Field::listing('opleveringsniveau')->select('./Opleveringsniveau/Voorziening'),
			Field::boolean('flexplek')->select('./FlexPlek'),
		)),
		Subtype::make('winkelruimte', './Functies/Winkelruimte', array(
			Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
			Field::int('inUnitsVanaf')->select('./InUnitsVanaf'),
			Field::int('verkoopVloeroppervlakte')->select('./VerkoopVloeroppervlakte')->formatter('area'),
			Field::boolean('bijdrageWinkeliersvereniging')->select('./BijdrageWinkeliersvereniging'),
			Field::int('goodwillPrijs')->select('./TerOvername/PrijsInventarisGoodwill/Prijs')->formatter('money'),
			Field::string('goodwillBTWTarief'),
			Field::boolean('goodwillBTWBelast')->select('./TerOvername/PrijsInventarisGoodwill/BTWBelast'),
			Field::boolean('terOvernamePersoneel')->select('./TerOvername/Personeel'),
			Field::int('verdiepingen')->select('./Verdiepingen'),
			Field::int('frontbreedte')->select('./Frontbreedte'),
			Field::boolean('branchebeperking')->select('./Branchebeperking'),
			Field::boolean('horecaToegestaan')->select('./HorecaToegestaan'),
			Field::string('welstandsklasse')->select('./Welstandsklasse'),
		)),
	)),
	Subtype::make('bouwgrond', './Functies/Bouwgrond', array(
		Field::string('bebouwingsmogelijkheid')->select('./Bebouwingsmogelijkheid'),
		Field::int('volumeProcentueel')->select('./Bouwvolume/Procentueel'),
		Field::int('volumeInVierkanteMeters')->select('./Bouwvolume/InVierkanteMeters'),
		Field::int('volumeBouwhoogte')->select('./Bouwvolume/Bouwhoogte'),
		Field::int('inUnitsVanaf')->select('./InUnitsVanaf'),
	)),
	Subtype::collection('medialijst', './MediaLijst/Media', array(
		Field::string('groep')->select('./Groep'),
		Field::string('url')->select('./URL')->length(1000),
		Field::string('omschrijving')->select('./MediaOmschrijving')->length(1000),
		Field::date('gewijzigd')->select('./LaatsteWijziging')->parseFormat('Y-m-d\TH:i:s'),
	)),
	Field::boolean('prijsTonen')->select('./Web/PrijsTonen'),
	Field::int('prioriteit')->select('./Web/Prioriteit'),
	Field::string('korteOmschrijving')->select('./Web/KorteOmschrijving'),
);
