<?php

use CustomPost\Fields\Field;
use CustomPost\Fields\Subtype;
use Realworks\Common\PrimaryKeySelector;
use Realworks\Nieuwbouw\Nummer\Selectors\AddressSelector;

return array(
	Field::int('id')->select(new PrimaryKeySelector)->primary()->unique(),
	Field::string('user'),
	Field::string('NVMVestigingNR')->select('./NVMVestigingNR'),
	Field::string('objectAfdeling')->select('./ObjectAfdeling'),
	Field::int('objectTiaraID')->select('./ObjectTiaraID'),
	Field::int('objectSystemID')->select('./ObjectSystemID'),
	Field::string('objectCode')->select('./ObjectCode'),
	Field::string('adres')->select(new AddressSelector),
	Field::string('straatnaam')->select('./BouwNummerDetails/Adres/Straatnaam'),
	Field::string('bouwnummer')->select('./BouwnummerCode'),
	Field::int('huisnummer')->select('./BouwNummerDetails/Adres/Huisnummer'),
	Field::string('huisnummerToevoeging')->select('./BouwNummerDetails/Adres/HuisnummerToevoeging'),
	Field::string('postcode')->select('./BouwNummerDetails/Adres/Postcode'),
	Field::string('plaats')->select('./BouwNummerDetails/Adres/Woonplaats')->formatter('Realworks\Common\Formatters\CityFormatter')->hasVirtualDependency(true),
	Field::int('koopprijs')->select('./BouwNummerDetails/Financieel/Koop/Koopprijs')->formatter('money'),
	Field::string('koopconditie')->select('./BouwNummerDetails/Financieel/Koop/KoopConditie'),
	Field::string('koopspecificatie')->select('./BouwNummerDetails/Financieel/Koop/KoopSpecificatie'),
	Field::int('WOZWaarde')->select('./BouwNummerDetails/Financieel/Koop/WOZ/WOZWaarde')->formatter('money'),
	Field::date('WOZWaardePeildatum')->select('./BouwNummerDetails/Financieel/Koop/WOZ/WOZWaardePeildatum')->parseFormat('Y-m-d'),
	Field::int('huurprijs')->select('./BouwNummerDetails/Financieel/Huur/Huurprijs')->formatter('money'),
	Field::string('huurconditie')->select('./BouwNummerDetails/Financieel/Huur/HuurConditie'),
	Field::string('huurspecificatie')->select('./BouwNummerDetails/Financieel/Huur/HuurSpecificatie'),
	Field::int('servicekostenPerMaand')->select('./BouwNummerDetails/Financieel/ServicekostenPerMaand')->formatter('money'),
	Field::date('datumInvoer')->select('./BouwNummerDetails/DatumInvoer')->parseFormat('Y-m-d'),
	Field::date('datumWijziging')->select('./BouwNummerDetails/DatumWijziging')->parseFormat('Y-m-d'),
	Field::string('status')->select('./BouwNummerDetails/Status/ObjectStatus')->values(array(
		'Beschikbaar' => 'Beschikbaar',
		'Onder bod' => 'Onder bod',
		'Onder optie' => 'Onder optie',
		'Verkocht onder voorbehoud' => 'Verkocht onder voorbehoud',
		'Verhuurd onder voorbehoud' => 'Verhuurd onder voorbehoud',
		'Verkocht' => 'Verkocht',
		'Verhuurd' => 'Verhuurd',
		'Ingetrokken' => 'Ingetrokken',
		'Geveild' => 'Geveild',
	)),
	Field::date('datumVoorbehoudTot')->select('./BouwNummerDetails/Status/DatumVoorbehoudTot')->parseFormat('Y-m-d'),
	Field::date('transactieDatum')->select('./BouwNummerDetails/Status/TransactieDatum')->parseFormat('Y-m-d'),
	Field::text('aanbiedingstekst')->select('./BouwNummerDetails/Aanbiedingstekst'),
	Subtype::make('woning', './BouwNummerDetails/Wonen', array(
		Field::listing('liggingen')->select('./Details/MatenEnLigging/Liggingen/Ligging'),
		Field::int('inhoud')->select('./Details/MatenEnLigging/Inhoud')->formatter('volume'),
		Field::int('totaleWoonOppervlakte')->select('./Details/MatenEnLigging/TotaleWoonOppervlakte')->formatter('area'),
		Field::int('gebruiksoppervlakteWoonfunctie')->select('./Details/MatenEnLigging/GebruiksoppervlakteWoonfunctie')->formatter('area'),
		Field::int('gebruiksoppervlakteOverigeFuncties')->select('./Details/MatenEnLigging/GebruiksoppervlakteOverigeFuncties')->formatter('area'),
		Field::int('buitenruimtesGebouwgebondenOfVrijstaand')->select('./Details/MatenEnLigging/BuitenruimtesGebouwgebondenOfVrijstaand')->formatter('area'),
		Field::int('perceelOppervlakte')->select('./Details/MatenEnLigging/PerceelOppervlakte')->formatter('area'),
		Subtype::make('installatie', './Details/Installatie', array(
			Field::listing('soortenVerwarming')->select('./SoortenVerwarming/Verwarming'),
			Field::string('CVKetelType')->select('./CVKetel/CVKetelType'),
			Field::int('CVKetelBouwjaar')->select('./CVKetel/Bouwjaar')->formatter('string'),
			Field::string('CVKetelBrandstof')->select('./CVKetel/Brandstof'),
			Field::string('CVKetelEigendom')->select('./CVKetel/Eigendom'),
			Field::boolean('CVKetelCombiketel')->select('./CVKetel/Combiketel')->trueValue('ja'),
			Field::listing('soortenWarmWater')->select('./SoortenWarmWater/WarmWater'),
		)),
		Subtype::make('tuin', './Details/Tuin', array(
			Field::listing('tuintypen')->select('./Tuintypen/Tuintype'),
			Field::string('kwaliteit')->select('./Kwaliteit'),
			Field::int('totaleOppervlakte')->select('./TotaleOppervlakte')->formatter('area'),
		)),
		Subtype::make('hoofdtuin', './Details/Tuin/Hoofdtuin', array(
			Field::string('type')->select('./Type'),
			Field::string('positie')->select('./Positie'),
			Field::boolean('achterom')->select('./Achterom')->trueValue('ja'),
			Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
			Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
			Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
		)),
		Subtype::make('schuurBerging', './Details/SchuurBerging', array(
			Field::string('soort')->select('./Soort'),
			Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
			Field::listing('isolatievormen')->select('./Isolatievormen/Isolatie'),
			Field::int('totaalAantal')->select('./TotaalAantal'),
		)),
		Subtype::make('garage', './Details/Garage', array(
			Field::listing('soorten')->select('./Soorten/Soort'),
			Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
			Field::int('capaciteit')->select('./Capaciteit'),
			Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
			Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
			Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			Field::listing('isolatievormen')->select('./Isolatievormen/Isolatie'),
			Field::int('totaalAantalGarages')->select('./TotaalAantalGarages'),
		)),
		Field::listing('bijzonderheden')->select('./Details/Diversen/Bijzonderheden/Bijzonderheid'),
		Field::listing('isolatievormen')->select('./Details/Diversen/Isolatievormen/Isolatie'),
		Field::string('dakType')->select('./Details/Diversen/Dak/Type'),
		Field::listing('dakMaterialen')->select('./Details/Diversen/Dak/Materialen/Materiaal'),
		Field::string('dakToelichting')->select('./Details/Diversen/Dak/Toelichting')->length(1000),
		Subtype::make('woonhuis', './Woonhuis', array(
			Field::string('soort')->select('./SoortWoning'),
			Field::string('type')->select('./TypeWoning'),
			Field::string('kenmerk')->select('./KenmerkWoning'),
			Field::string('kwaliteit')->select('./KwaliteitWoning'),
		)),
		Subtype::make('appartement', './Appartement', array(
			Field::string('soort')->select('./SoortAppartement'),
			Field::string('kenmerk')->select('./KenmerkAppartement'),
			Field::string('kwaliteit')->select('./KwaliteitAppartement'),
			Field::boolean('openPortiek')->select('./OpenPortiek')->trueValue('ja'),
			Field::int('woonlaag')->select('./Woonlaag'),
			Field::int('aantalWoonlagen')->select('./AantalWoonlagen'),
			Field::boolean('VVEActief')->select('./VVEActief')->trueValue('ja'),
		)),
		Field::int('aantalVerdiepingen')->select('./Verdiepingen/Aantal'),
		Field::int('aantalKamers')->select('./Verdiepingen/AantalKamers'),
		Field::int('aantalSlaapkamers')->select('./Verdiepingen/AantalSlaapKamers'),
		Subtype::make('kelder', './Woonlagen/Kelder', array(
			Field::int('verdiepingNr')->select('./VerdiepingNr'),
			Field::string('naam')->select('./Naam'),
			Field::int('aantalKamers')->select('./AantalKamers'),
			Field::int('aantalSlaapkamers')->select('./AantalSlaapkamers'),
			Subtype::make('woonkamer', './Woonkamer', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::boolean('trap')->select('./Trap')->trueValue('ja'),
			)),
			Subtype::make('keuken', './Keuken', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::int('vernieuwd')->select('./Vernieuwd'),
			)),
			Subtype::make('badkamer', './Badkamer[0]', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Subtype::collection('badkamers', './Badkamer', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Field::listing('overigeRuimten')->select('./OverigeRuimten/OverigeRuimte'),
		)),
		Subtype::make('beganeGrondOfFlat', './Woonlagen/BeganeGrondOfFlat', array(
			Field::int('verdiepingNr')->select('./VerdiepingNr'),
			Field::string('naam')->select('./Naam'),
			Field::int('aantalKamers')->select('./AantalKamers'),
			Field::int('aantalSlaapkamers')->select('./AantalSlaapkamers'),
			Subtype::make('woonkamer', './Woonkamer', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::boolean('trap')->select('./Trap')->trueValue('ja'),
			)),
			Subtype::make('keuken', './Keuken', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::int('vernieuwd')->select('./Vernieuwd'),
			)),
			Subtype::make('badkamer', './Badkamer[0]', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Subtype::collection('badkamers', './Badkamer', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Field::listing('overigeRuimten')->select('./OverigeRuimten/OverigeRuimte'),
		)),
		Subtype::make('verdieping', './Woonlagen/Verdieping', array(
			Field::int('verdiepingNr')->select('./VerdiepingNr'),
			Field::string('naam')->select('./Naam'),
			Field::int('aantalKamers')->select('./AantalKamers'),
			Field::int('aantalSlaapkamers')->select('./AantalSlaapkamers'),
			Subtype::make('woonkamer', './Woonkamer', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::string('trap')->select('./Trap'),
			)),
			Subtype::make('keuken', './Keuken', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::int('vernieuwd')->select('./Vernieuwd'),
			)),
			Subtype::make('badkamer', './Badkamer[0]', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Subtype::collection('badkamers', './Badkamer', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Field::listing('overigeRuimten')->select('./OverigeRuimten/OverigeRuimte'),
		)),
		Subtype::make('zolder', './Woonlagen/Zolder', array(
			Field::int('verdiepingNr')->select('./VerdiepingNr'),
			Field::string('naam')->select('./Naam'),
			Field::int('aantalKamers')->select('./AantalKamers'),
			Field::int('aantalSlaapkamers')->select('./AantalSlaapkamers'),
			Subtype::make('woonkamer', './Woonkamer', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::string('trap')->select('./Trap'),
			)),
			Subtype::make('keuken', './Keuken', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::int('vernieuwd')->select('./Vernieuwd'),
			)),
			Subtype::make('badkamer', './Badkamer[0]', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Subtype::collection('badkamers', './Badkamer', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Field::listing('overigeRuimten')->select('./OverigeRuimten/OverigeRuimte'),
			Field::listing('zolderVlieringOpties')->select('./ZolderVlieringOpties/ZolderVlieringOptie'),
		)),
		Subtype::make('vliering', './Woonlagen/Vliering', array(
			Field::int('verdiepingNr')->select('./VerdiepingNr'),
			Field::string('naam')->select('./Naam'),
			Field::int('aantalKamers')->select('./AantalKamers'),
			Field::int('aantalSlaapkamers')->select('./AantalSlaapkamers'),
			Subtype::make('woonkamer', './Woonkamer', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::string('trap')->select('./Trap'),
			)),
			Subtype::make('keuken', './Keuken', array(
				Field::listing('types')->select('./Types/Type'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
				Field::int('vernieuwd')->select('./Vernieuwd'),
			)),
			Subtype::make('badkamer', './Badkamer[0]', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Subtype::collection('badkamers', './Badkamer', array(
				Field::listing('voorzieningen')->select('./Voorzieningen/Voorziening'),
				Field::int('lengte')->select('./Afmetingen/Lengte')->formatter('length'),
				Field::int('breedte')->select('./Afmetingen/Breedte')->formatter('length'),
				Field::int('oppervlakte')->select('./Afmetingen/Oppervlakte')->formatter('area'),
			)),
			Field::listing('overigeRuimten')->select('./OverigeRuimten/OverigeRuimte'),
			Field::listing('zolderVlieringOpties')->select('./ZolderVlieringOpties/ZolderVlieringOptie'),
		)),
	)),
	Subtype::collection('medialijst', './MediaLijst/Media', array(
		Field::string('groep')->select('./Groep'),
		Field::string('url')->select('./URL')->length(1000),
		Field::string('omschrijving')->select('./MediaOmschrijving'),
		Field::date('gewijzigd')->select('./MediaUpdate')->parseFormat('Y-m-d\TH:i:s'),
	)),
);
