<?php

use CustomPost\Fields\Field;
use CustomPost\Fields\Subtype;
use Realworks\Common\PrimaryKeySelector;
use Realworks\Alv\Selectors\AddressSelector;

return array(
	Field::int('id')->select(new PrimaryKeySelector)->primary()->unique(),
	Field::string('user'),
	Field::string('NVMVestigingNR')->select('./NVMVestigingNR'),
	Field::string('objectCompany')->select('./ObjectCompany'),
	Field::string('objectAfdeling')->select('./ObjectAfdeling'),
	Field::int('objectTiaraID')->select('./ObjectTiaraID'),
	Field::int('objectSystemID')->select('./ObjectSystemID'),
	Field::string('objectCode')->select('./ObjectCode'),
	Field::string('adres')->select(new AddressSelector),
	Field::string('plaats')->select('./ObjectDetails/Adres/Nederlands/Woonplaats')->formatter('Realworks\Common\Formatters\CityFormatter')->hasVirtualDependency(true),
	Subtype::make('adresNederlands', './ObjectDetails/Adres/Nederlands', array(
		Field::string('straatnaam')->select('./Straatnaam'),
		Field::int('hoofdnummer')->select('./Huisnummer/Hoofdnummer'),
		Field::int('reeksBegin')->select('./Huisnummer/Reeks/Begin'),
		Field::int('reeksEind')->select('./Huisnummer/Reeks/Eind'),
		Field::string('huisnummerToevoeging')->select('./HuisnummerToevoeging'),
		Field::string('postcode')->select('./Postcode'),
		Field::string('woonplaats')->select('./Woonplaats'),
		Field::string('provincie')->select('./Provincie'),
	)),
	Subtype::make('koop', './ObjectDetails/Koop', array(
		Field::string('prijsvoorvoegsel')->select('./Prijsvoorvoegsel'),
		Field::int('prijs')->select('./Koopprijs')->formatter('money'),
		Field::int('prijsPerHa')->select('./KoopprijsPerHa')->formatter('money'),
		Field::string('koopconditie')->select('./KoopConditie'),
		Field::string('koopspecificatie')->select('./KoopSpecificatie'),
	)),
	Subtype::make('veiling', './ObjectDetails/Veiling', array(
		Field::int('vanafprijs')->select('./Vanafprijs')->formatter('money'),
		Field::int('zoekprijs')->select('./Zoekprijs')->formatter('money'),
		Field::string('soortVeiling')->select('./SoortVeiling'),
		Field::string('veilingtype')->select('./Veilingtype'),
		Field::datetime('startDatumTijd')->select('./StartDatumTijd')->parseFormat('Y-m-d\TH:i:s'),
		Field::datetime('eindDatumTijd')->select('./EindDatumTijd')->parseFormat('Y-m-d\TH:i:s'),
		Field::string('veilingSiteNaam')->select('./VeilingSiteNaam'),
		Field::text('veilingSiteAdres')->select('./VeilingSiteAdres'),
	)),
	Field::string('aanvaarding')->select('./ObjectDetails/Aanvaarding'),
	Field::date('datumAanvaarding')->select('./ObjectDetails/DatumAanvaarding')->parseFormat('Y-m-d'),
	Field::string('objectAanmelding')->select('./ObjectDetails/ObjectAanmelding'),
	Field::date('datumInvoer')->select('./ObjectDetails/DatumInvoer')->parseFormat('Y-m-d'),
	Field::datetime('datumWijziging')->select('./ObjectDetails/DatumWijziging')->parseFormat('Y-m-d\TH:i:s'),
	Field::string('status')->select('./ObjectDetails/StatusBeschikbaarheid/Status')->values(array(
			'beschikbaar' => 'Beschikbaar',
			'onder bod' => 'Onder bod',
			'onder optie' => 'Onder optie',
			'verkocht onder voorbehoud' => 'Verkocht onder voorbehoud',
			'verkocht' => 'Verkocht',
			'geveild' => 'Geveild',
			'verkocht bij inschrijving' => 'Verkocht bij inschrijving',
			'in verpachte staat' => 'In verpachte staat',
			'ingetrokken' => 'Ingetrokken',
	)),
	Field::string('bouwvorm')->select('./ObjectDetails/Bouwvorm'),
	Subtype::collection('internetplaatsingen', './ObjectDetails/Internetplaatsingen/Internetplaatsing', array(
		Field::string('plaatsing')->select('./Plaatsing'),
		Field::bool('prijsvermelding')->select('./Prijsvermelding'),
		Field::bool('adresvermelding')->select('./Adresvermelding'),
	)),
	Field::text('aanbiedingstekst')->select('./ObjectDetails/Aanbiedingstekst'),
	Subtype::make('akkerbouwbedrijf', './AenLV/Hoofdfunctie/Akkerbouwbedrijf', array(
		Field::listing('grondsoorten')->select('./Grondsoorten/Grondsoort'),
		Subtype::collection('opslagschuren', './Opslagschuren/Opslagschuur', array(
			Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
		)),
		Subtype::collection('machineloodsen', './Machineloodsen/Machineloods', array(
			Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
		)),
		Field::string('productierechten')->select('./Productierechten'),
		Field::listing('overigeVoorzieningen')->select('./OverigeVoorzieningen/Voorziening'),
	)),
	Subtype::make('losseGrond', './AenLV/Hoofdfunctie/LosseGrond', array(
		Field::int('lengte')->select('./Lengte')->formatter('length'),
		Field::int('breedte')->select('./Breedte')->formatter('length'),
		Field::listing('grondsoorten')->select('./Grondsoorten/Grondsoort'),
		Field::listing('landTypes')->select('./TypenLand/TypeLand'),
	)),
	Subtype::make('manegePensionstalling', './AenLV/Hoofdfunctie/ManegePensionstalling', array(
		Field::int('paardenboxen')->select('./Paardenboxen'),
		Subtype::collection('rijhallen', './Rijhallen/Rijhal', array(
			Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
			Field::int('bouwjaar')->select('./Bouwjaar')->formatter('string'),
			Field::bool('kantine')->select('./Kantine'),
		)),
		Subtype::collection('loodsen', './Loodsen/Loods', array(
			Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
		)),
		Field::listing('overigeVoorzieningen')->select('./OverigeVoorzieningen/Voorziening'),
	)),
	Subtype::make('melkveehouderij', './AenLV/Hoofdfunctie/Melkveehouderij', array(
		Field::int('aantalLigboxen')->select('./AantalLigboxen'),
		Field::int('aantalJongveePlaatsen')->select('./AantalJongveePlaatsen'),
		Subtype::collection('opstanden', './Opstanden/Opstand', array(
			Field::string('omschrijving')->select('./Omschrijving'),
			Field::int('lengte')->select('./Lengte')->formatter('length'),
			Field::int('breedte')->select('./Breedte')->formatter('length'),
			Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
			Field::int('bouwjaar')->select('./Bouwjaar')->formatter('string'),
		)),
		Field::string('melksysteem')->select('./Melksysteem'),
		Field::listing('overigeVoorzieningen')->select('./OverigeVoorzieningen/Voorziening'),
	)),
	Subtype::make('overig', './AenLV/Hoofdfunctie/Overig', array(
		Field::string('typeOnderneming')->select('./TypeOnderneming'),
		Subtype::collection('opstallen', './Opstallen/Opstal', array(
			Field::string('omschrijving')->select('./Omschrijving'),
			Field::int('bouwjaar')->select('./Bouwjaar')->formatter('string'),
		)),
		Field::listing('installaties')->select('./Installaties/Installatie'),
		Field::listing('overigeVoorzieningen')->select('./OverigeVoorzieningen/Voorziening'),
		Field::listing('grondsoorten')->select('./Grondsoorten/Grondsoort'),
	)),
	Subtype::make('paardenhouderij', './AenLV/Hoofdfunctie/Paardenhouderij', array(
		Field::int('paardenboxen')->select('./Paardenboxen'),
		Subtype::collection('rijhallen', './Rijhallen/Rijhal', array(
			Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
			Field::int('bouwjaar')->select('./Bouwjaar')->formatter('string'),
			Field::bool('kantine')->select('./Kantine'),
		)),
		Field::int('loopstalOppervlakte')->select('./Loopstal/Oppervlakte'),
		Subtype::collection('loodsen', './Loodsen/Loods', array(
			Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
		)),
		Field::listing('afrasteringen')->select('./Afrasteringen/Afrastering'),
		Field::listing('overigeVoorzieningen')->select('./OverigeVoorzieningen/Voorziening'),
	)),
	Subtype::make('pluimveebedrijf', './AenLV/Hoofdfunctie/Pluimveebedrijf', array(
		Field::string('typeOnderneming')->select('./TypeOnderneming'),
		Field::listing('typenHuisvesting')->select('./TypenHuisvesting/TypeHuisvesting'),
		Field::int('bouwjaar')->select('./Bouwjaar')->formatter('string'),
		Subtype::collection('mestsilos', './Mestsilos/Mestsilo', array(
			Field::int('inhoud')->select('./Inhoud')->formatter('volume'),
		)),
		Field::int('pluimveerechten')->select('./Pluimveerechten'),
		Field::bool('groenlabel')->select('./Groenlabel'),
	)),
	Subtype::make('tuinbouwbedrijf', './AenLV/Hoofdfunctie/Tuinbouwbedrijf', array(
		Field::string('typeOnderneming')->select('./TypeOnderneming'),
		Field::listing('teeltTypes')->select('./TeeltTypen/TeeltType'),
		Subtype::make('grond', './Grond', array(
			Field::int('kavellengte')->select('./Kavellengte')->formatter('length'),
			Field::int('kavelBreedte')->select('./KavelBreedte')->formatter('length'),
			Field::int('bebouwdeBreedte')->select('./BebouwdeBreedte')->formatter('length'),
			Field::listing('grondsoorten')->select('./Grondsoorten/Grondsoort'),
			Field::bool('drainage')->select('./Drainage'),
		)),
		Subtype::collection('glasOpstanden', './GlasOpstanden/GlasOpstand', array(
			Field::int('lengte')->select('./Lengte')->formatter('length'),
			Field::int('breedte')->select('./Breedte')->formatter('length'),
			Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
			Field::int('bouwjaar')->select('./Bouwjaar')->formatter('string'),
			Field::string('onderbouw')->select('./Onderbouw'),
			Field::string('typeKas')->select('./TypeKas'),
			Field::string('poothoogte')->select('./Poothoogte'),
			Field::string('kapbreedte')->select('./Kapbreedte'),
			Field::string('vakafstand')->select('./Vakafstand'),
			Field::listing('overigeVoorzieningen')->select('./OverigeVoorzieningen/Voorziening'),
		)),
		Subtype::collection('overigeOpstanden', './OverigeOpstanden/Opstand', array(
			Field::string('omschrijving')->select('./Omschrijving'),
			Field::int('lengte')->select('./Lengte')->formatter('length'),
			Field::int('breedte')->select('./Breedte')->formatter('length'),
			Field::int('oppervlakte')->select('./Oppervlakte')->formatter('area'),
			Field::int('bouwjaar')->select('./Bouwjaar')->formatter('string'),
		)),
		Field::listing('installaties')->select('./Installaties/Installatie'),
		Field::int('erfverharding')->select('./Erfverharding'),
	)),
	Subtype::make('varkenshouderij', './AenLV/Hoofdfunctie/Varkenshouderij', array(
		Field::string('typeOnderneming')->select('./TypeOnderneming'),
		Field::int('aantalVleesvarkens')->select('./AantalVleesvarkens'),
		Field::int('aantalFokvarkens')->select('./AantalFokvarkens'),
		Field::int('aantalBiggen')->select('./AantalBiggen'),
		Field::int('aantalVleesvarkensstallen')->select('./AantalVleesvarkensstallen'),
		Field::int('aantalFokvarkensstallen')->select('./AantalFokvarkensstallen'),
		Field::int('aantalBiggenstallen')->select('./AantalBiggenstallen'),
		Field::int('bouwjaar')->select('./Bouwjaar'),
		Subtype::collection('mestsilos', './Mestsilos/Mestsilo', array(
			Field::int('inhoud')->select('./Inhoud')->formatter('volume'),
		)),
		Field::int('varkensrechten')->select('./Varkensrechten'),
		Field::listing('overigeVoorzieningen')->select('./OverigeVoorzieningen/Voorziening'),
	)),
	Subtype::make('vleeskalverenbedrijf', './AenLV/Hoofdfunctie/Vleeskalverenbedrijf', array(
		Field::int('aantalKalveren')->select('./AantalKalveren'),
		Field::int('bouwjaar')->select('./Bouwjaar')->formatter('string'),
		Subtype::collection('mestsilos', './Mestsilos/Mestsilo', array(
			Field::int('inhoud')->select('./Inhoud')->formatter('volume'),
		)),
		Field::listing('overigeVoorzieningen')->select('./OverigeVoorzieningen/Voorziening'),
	)),
	Subtype::make('nevenfunctie', './AenLV/Nevenfunctie', array(
		Field::string('agrarisch')->select('./FunctieAgrarisch'),
		Field::listing('nietAgrarisch')->select('./FunctieNietAgrarisch/Functie'),
		Field::string('nietAgrarischOverig')->select('./FunctieNietAgrarisch/Overig'),
	)),
	Subtype::collection('bouwkavels', './AenLV/Bouwkavels/Bouwkavel', array(
		Field::int('hectare')->select('./Oppervlakte/Hectare'),
		Field::int('are')->select('./Oppervlakte/Are'),
		Field::int('centiare')->select('./Oppervlakte/Centiare'),
	)),
	Subtype::make('veldkavelsOppervlakte', './AenLV/VeldkavelsOppervlakte', array(
		Field::int('hectare')->select('./Hectare'),
		Field::int('are')->select('./Are'),
		Field::int('centiare')->select('./Centiare'),
	)),
	Subtype::make('huiskavelOppervlakte', './AenLV/HuiskavelOppervlakte', array(
		Field::int('hectare')->select('./Hectare'),
		Field::int('are')->select('./Are'),
		Field::int('centiare')->select('./Centiare'),
	)),
	Field::string('aantalBedrijfswoningen')->select('./AenLV/Bedrijfswoningen/AantalBedrijfswoningen'),
	Subtype::make('hoofdwoning', './AenLV/Bedrijfswoningen/Hoofdwoning', array(
		Field::int('brutoInhoud')->select('./BrutoInhoud')->formatter('volume'),
		Field::int('bouwjaar')->select('./Bouwjaar/JaarOmschrijving/Jaar')->formatter('string'),
		Field::string('bouwjaarOmschrijving')->select('./Bouwjaar/JaarOmschrijving/Omschrijving'),
		Field::string('bouwjaarPeriode')->select('./Bouwjaar/Periode'),
		Field::string('onderhoudBinnenWaardering')->select('./Onderhoud/Binnen/Waardering'),
		Field::string('onderhoudBuitenWaardering')->select('./Onderhoud/Buiten/Waardering'),
		Field::string('energieklasse')->select('./Energielabel/Energieklasse'),
		Field::string('energieIndex')->select('./Energielabel/EnergieIndex'),
		Field::date('energielabelEinddatum')->select('./Energielabel/Einddatum')->parseFormat('Y-m-d'),
		Field::string('EPC')->select('./EPC'),
	)),
	Subtype::collection('kadastraleInformatie', './Kadaster/KadastraleInformatie', array(
		Field::int('kadaterID')->select('./KadastraalID'),
		Field::string('gemeente')->select('./KadastraleGegevens/KadastraleGemeente'),
		Field::string('sectie')->select('./KadastraleGegevens/Sectie'),
		Field::string('perceel')->select('./KadastraleGegevens/Perceel'),
		Field::int('hectare')->select('./KadastraleGegevens/Oppervlakte/Hectare'),
		Field::int('are')->select('./KadastraleGegevens/Oppervlakte/Are'),
		Field::int('centiare')->select('./KadastraleGegevens/Oppervlakte/Centiare'),
		Field::string('omvang')->select('./KadastraleGegevens/Omvang'),
		Field::string('eigendomSoort')->select('./EigendomsGegevens/Soort'),
	)),
	Field::listing('medeAanmelders')->select('./MedeAanmelders/MedeAanmelder'),
	Subtype::collection('mediaLijst', './MediaLijst/Media', array(
		Field::string('groep')->select('./Groep'),
		Field::string('URL')->select('./URL')->length(1000),
		Field::string('omschrijving')->select('./MediaOmschrijving')->length(1000),
		Field::datetime('gewijzigd')->select('./MediaUpdate')->parseFormat('Y-m-d\TH:i:s'),
	)),
	Field::bool('prijsTonen')->select('./Web/PrijsTonen'),
	Field::datetime('openHuisVanaf')->select('./Web/OpenHuis/Vanaf')->parseFormat('Y-m-d\TH:i:s'),
	Field::datetime('openHuisTot')->select('./Web/OpenHuis/Tot')->parseFormat('Y-m-d\TH:i:s'),
	Field::int('prioriteit')->select('./Web/Prioriteit'),
	Field::text('korteOmschrijving')->select('./Web/KorteOmschrijving'),
	Field::string('transactieConditie')->select('./Transactiegegevens/TransactieConditie'),
);
